FROM            mb-project:base
MAINTAINER      pmb.dev3@gmail.com

ENV             BUILD_MODE              dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

# dev용 requirements설치
COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt

COPY            .   /srv/project

# Nginx 설정파일들 복사 및 enabled로 링크
RUN             cp -f   /srv/project/.config/${BUILD_MODE}/nginx.conf \
                        /etc/nginx/nginx.conf && \
                cp -f   /srv/project/.config/${BUILD_MODE}/nginx_app.conf \
                        /etc/nginx/sites-available/ && \
                rm -f   /etc/nginx/sites-enabled/* && \
                ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                        /etc/nginx/sites-enabled/

# supervisor설정 복사
RUN             cp -f   /srv/project/.config/${BUILD_MODE}/supervisor.conf \
                        /etc/supervisor/conf.d/

# supervisord실행
CMD             supervisord -n